ETSa:1:{s:4:"main";a:3:{s:5:"2:174";s:163:"

<table class="nlb_table" width="97%">
	<tr>
		<th width="50%">
			Subject
		</th>
		<th>
			Author
		</th>
		<th>
			Date Published
		</th>
	</tr>
";s:16:"16:189:articles:";a:11:{s:5:"2:218";s:29:"
	<tr>
		<td>
			<a href="";s:18:"4:230:url_article:";s:0:"";s:5:"2:233";s:2:"">";s:14:"4:241:subject:";s:0:"";s:5:"2:277";s:35:"</a>
		</td>
		<td>
			<a href="";s:25:"4:296:author_url_profile:";s:0:"";s:5:"2:299";s:2:"">";s:13:"4:306:author:";s:0:"";s:5:"2:333";s:26:"</a>
		</td>
		<td>
			";s:11:"4:338:date:";s:0:"";s:5:"2:358";s:19:"
		</td>
	</tr>
";}s:5:"2:381";s:16:"

</table>

";}}