ETSa:1:{s:4:"main";a:11:{s:4:"2:22";s:11:"

	<p>
	";s:20:"32:41:url_page_prev:";a:3:{s:4:"2:54";s:13:"
		<a href="";s:19:"4:68:url_page_prev:";s:0:"";s:4:"2:89";s:20:"">Back a page</a>
	";}s:5:"2:100";s:5:"

	";s:21:"32:119:url_page_next:";a:3:{s:5:"2:132";s:13:"
		<a href="";s:20:"4:146:url_page_next:";s:0:"";s:5:"2:165";s:18:"">Next Page</a>
	";}s:5:"2:316";s:145:"
	</p>
	<center>
		<table width="95%" class="nlb_table">
			<tr>
				<th>Subject</th>
				<th>Date</th>
				<th>Options</th>
			</tr>
		";s:12:"16:327:list:";a:11:{s:5:"2:356";s:29:"
			<tr>
				<td> <a href="";s:15:"4:365:url_view:";s:0:"";s:5:"2:430";s:64:"" onMouseOver="return overlib('View Item');" onMouseOut="nd();">";s:14:"4:438:subject:";s:0:"";s:5:"2:460";s:21:"</a> </td>
				<td> ";s:11:"4:465:date:";s:0:"";s:5:"2:499";s:33:" </td>
				<td> 
					<a href="";s:15:"4:508:url_edit:";s:0:"";s:5:"2:597";s:88:"" onMouseOver="return overlib('Edit Item');" onMouseOut="nd();">Edit</a>
					<a href="";s:17:"4:608:url_delete:";s:0:"";s:5:"2:711";s:102:"" onMouseOver="return overlib('Delete Item');" onMouseOut="nd();">Delete</a> 
				</td>
			</tr>
		";}s:5:"2:751";s:33:"
		</table>
	</center>
	<p>
	";s:21:"32:770:url_page_prev:";a:3:{s:5:"2:783";s:13:"
		<a href="";s:20:"4:797:url_page_prev:";s:0:"";s:5:"2:818";s:20:"">Back a page</a>
	";}s:5:"2:829";s:5:"

	";s:21:"32:848:url_page_next:";a:3:{s:5:"2:861";s:13:"
		<a href="";s:20:"4:875:url_page_next:";s:0:"";s:5:"2:894";s:18:"">Next Page</a>
	";}s:5:"2:909";s:9:"
	</p>
";}}