ETSa:3:{s:4:"main";a:11:{s:5:"2:296";s:284:"

<!-- End of Content -->
<br>
		</TD>
		<TD VALIGN="top" width="15%" BGCOLOR="#ffffff">
			<br>
			<!-- User Welcome Table -->
			<TABLE CELLSPACING="0" CELLPADDING="0" WIDTH="98%" BORDER="0">
				<tr>
					<td class="mltop">Welcome</td>
				</tr>
				<tr>
					<TD CLASS="ml">
					";s:15:"16:310:welcome:";a:5:{s:5:"2:317";s:7:"
						";s:16:"32:331:username:";a:11:{s:5:"2:345";s:14:"
							Hello ";s:15:"4:354:username:";s:0:"";s:5:"2:393";s:38:"!
							<li><a class="menubar" href="";s:13:"4:400:url_cp:";s:0:"";s:5:"2:453";s:52:"">Post Blog</a>
							<li><a class="menubar" href="";s:16:"4:463:url_blogs:";s:0:"";s:5:"2:517";s:53:"">View Blogs</a>
							<li><a class="menubar" href="";s:18:"4:529:url_friends:";s:0:"";s:5:"2:585";s:55:"">Friends Page</a>
							<li><a class="menubar" href="";s:17:"4:596:url_logout:";s:0:"";s:5:"2:616";s:19:"">Logout</a>
						";}s:5:"2:626";s:7:"
						";s:17:"128:640:username:";a:5:{s:5:"2:697";s:57:"
							Hi guest, please
							<a class="menubar" href="";s:16:"4:707:url_login:";s:0:"";s:5:"2:755";s:47:"">Login</a>
							or <a class="menubar" href="";s:19:"4:768:url_register:";s:0:"";s:5:"2:791";s:22:"">Register</a>	
						";}s:5:"2:800";s:6:"
					";}s:6:"2:1048";s:241:"
					</td>
				</tr>
			</TABLE><BR>
			<!-- end user welcome table -->
						
			<!-- Recen Blogs Table -->
			<TABLE CELLSPACING="0" CELLPADDING="0" WIDTH="100%" BORDER="0">
				<TR>
					<TD CLASS="mltop">Recent Blogs</TD>
				</TR>
				";s:22:"128:1066:recent_blogs:";a:1:{s:6:"2:1107";s:41:"<tr><TD CLASS="ml">No new Blogs</td></td>";}s:6:"2:1118";s:5:"
				";s:21:"16:1137:recent_blogs:";a:11:{s:6:"2:1207";s:70:"
				<tr>
					<TD CLASS="ml">
						<A CLASS="menubar" 
							HREF="";s:16:"4:1216:url_blog:";s:0:"";s:6:"2:1266";s:49:"" 
							onMouseOver="return overlib('Posted by ";s:14:"4:1273:author:";s:0:"";s:6:"2:1282";s:8:"<br>At: ";s:12:"4:1287:date:";s:0:"";s:6:"2:1302";s:14:"<br>Comments: ";s:9:"1024:1309";a:1:{s:6:"2:1310";s:1:"c";}s:6:"2:1356";s:45:"', LEFT);" 
							onMouseOut="nd();">
						";s:9:"1024:1363";a:1:{s:6:"2:1364";s:1:"s";}s:6:"2:1395";s:30:"</A>
					</td>
				</tr>
				";}s:6:"2:1852";s:450:"
			</TABLE><BR>
			<!-- end recent blogs table -->
		</TD>
	</TR>
</TABLE>

<TABLE WIDTH="97%" BORDER="0" CELLSPACING="1" CELLPADDING="0" ALIGN="center">
	<TR>
		<TD ALIGN="center" class="copyright">
			Powered by <a href="http://www.sevengraff.com" target="_blank" onMouseOver="return overlib('NewLife Blogging System v 3.0<br>&copy Copyright 2004 Sevengraff', ABOVE, CENTER);" onMouseOut="nd();"><b>NewLife Blogger</b></a>
			<br>
			Generated in ";s:16:"4:1861:gen_time:";s:0:"";s:6:"2:1877";s:15:" seconds using ";s:19:"4:1889:query_count:";s:0:"";s:6:"2:2025";s:135:" queries.
		</TD>
	</TR>
</TABLE>
<br>
</BODY>
</HTML>
<!--
	layout based on ArtisticO by iamthebest2
	Free template from oswd.org
-->
";}s:1:"s";a:2:{s:15:"4:2050:subject:";s:0:"";s:17:"128:2064:subject:";a:1:{s:6:"2:2081";s:17:"<i>No Subject</i>";}}s:1:"c";a:2:{s:16:"4:2112:comments:";s:0:"";s:18:"128:2127:comments:";a:1:{s:6:"2:2142";s:15:"<i>disabled</i>";}}}