ETSa:1:{s:4:"main";a:21:{s:5:"2:181";s:168:"
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>

<!--
	layout based on ArtisticO by iamthebest2
	Free template from oswd.org
-->

<HEAD>
<TITLE>";s:17:"4:192:main_title:";s:0:"";s:5:"2:516";s:323:"</TITLE>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<META NAME="DESCRIPTION" 	CONTENT="Free Multi-User web log software">
<META NAME="KEYWORDS" 		CONTENT="Free, Blog, web log, NewLife, NewLife Blogger, NLB, Sevengraff, GPL, Multi-User">
<META NAME="AUTHOR" 		CONTENT="Sevengraff">
<LINK HREF="";s:18:"4:528:script_path:";s:0:"";s:5:"2:716";s:187:"skin/style.css" TYPE="text/css" REL="stylesheet"> 
</HEAD>

<BODY>
<div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000;"></div>
<script language="JavaScript" src="";s:18:"4:728:script_path:";s:0:"";s:6:"2:1825";s:1096:"skin/overlib.js"></script>
<!-- 
	ToolTips by OverLib
	http://www.bosrup.com/web/overlib/
	overLIB (c) Erik Bosrup 
-->
<script language="JavaScript" type="text/javascript">
var ol_offsetx 		= 15;
var ol_fgcolor 		= "#D3DEE4";
var ol_bgcolor 		= "#000000";
var ol_capcolor 	= "#ffffff";
var ol_closecolor 	= "#ffffff";
var ol_width 		= "250";
</script>

<TABLE WIDTH="97%" BORDER="0" CELLSPACING="1" CELLPADDING="0" BGCOLOR="#000000" ALIGN="center">
	<TR>
		<TH COLSPAN="3"> 
			<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
				<TR>
					<TD CLASS="bg" HEIGHT="31" ALIGN="left">&nbsp;<FONT SIZE=4><B>NewLife Blogger v3.0</B></FONT></TD>
					<TD CLASS="bg" WIDTH="224" HEIGHT="31" ALIGN="right">
						<a href="http://www.sevengraff.com"><FONT color="black" SIZE=2>sevengraff.com</FONT></a>
						&nbsp;&nbsp;
					</TD>
				</TR>
			 </TABLE>
		</TH>
	</TR>

	<TR>
		<TD VALIGN="top" width="15%" BGCOLOR="#ffffff"><BR>
			<TABLE CELLSPACING="0" CELLPADDING="0" WIDTH="100%" BORDER="0">
				<TR>
					<TD CLASS="mltop">Options</TD>
				</TR>
				<TR>
					<TD CLASS="ml">
					";s:16:"16:1839:sitenav:";a:5:{s:6:"2:1873";s:34:"
						» <A CLASS="menubar" HREF="";s:12:"4:1878:link:";s:0:"";s:6:"2:1881";s:2:"">";s:12:"4:1886:text:";s:0:"";s:6:"2:1896";s:9:"</A><BR> ";}s:6:"2:1943";s:40:"
					</TD>
				</TR>
			</TABLE><BR>
		";s:16:"32:1956:usernav:";a:5:{s:6:"2:2056";s:100:"
			<TABLE CELLSPACING="0" CELLPADDING="0" WIDTH="100%" BORDER="0">
				<TR>
					<TD CLASS="mltop">";s:15:"4:2064:navtype:";s:0:"";s:6:"2:2116";s:51:"</TD>
				</TR>
				<TR>
					<TD CLASS="ml">
					";s:16:"16:2130:usernav:";a:5:{s:6:"2:2164";s:34:"
						» <A CLASS="menubar" HREF="";s:12:"4:2169:link:";s:0:"";s:6:"2:2172";s:2:"">";s:12:"4:2177:text:";s:0:"";s:6:"2:2187";s:9:"</A><BR> ";}s:6:"2:2235";s:41:"
					</TD>
				</TR>
		 	</TABLE><BR>
		";}s:6:"2:2581";s:340:"
		<!-- Buttons and credits -->
			<TABLE CELLSPACING="0" CELLPADDING="0" WIDTH="100%" BORDER="0">
				<TR>
					<TD CLASS="mltop">Credits</TD>
				</TR>
				<TR>
					<TD CLASS="ml">
						<A CLASS="menubar" HREF="http://www.php.net" target="_blank" onMouseOver="return overlib('PHP: Hypertext Preprocessor')" onMouseOut="nd();"><img src="";s:19:"4:2593:script_path:";s:0:"";s:6:"2:2771";s:177:"skin/powered_php.png"></A><BR>
						<A CLASS="menubar" HREF="http://www.mysql.org" target="_blank" onMouseOver="return overlib('MySQL Database');" onMouseOut="nd();"><img src="";s:19:"4:2783:script_path:";s:0:"";s:6:"2:2979";s:195:"skin/powered_mysql.png"></a><br>
						<A CLASS="menubar" HREF="http://www.sevengraff.com" target="_blank" onMouseOver="return overlib('Sevengraff Unlimited Media')" onMouseOut="nd();"><img src="";s:19:"4:2991:script_path:";s:0:"";s:6:"2:3176";s:184:"skin/powered_sum.gif"></A><BR>
						<A CLASS="menubar" HREF="http://ets.sf.net" target="_blank" onMouseOver="return overlib('ETS: Easy Template System')" onMouseOut="nd();"><img src="";s:19:"4:3188:script_path:";s:0:"";s:6:"2:3344";s:155:"skin/powered_ets.gif"></A><BR><BR>
					</TD>
				</TR>
			</TABLE><BR>
		</TD>
		<TD CLASS="content" VALIGN="top" align="left"><BR>
			<div class="title">";s:18:"4:3355:page_title:";s:0:"";s:6:"2:3387";s:31:"</div>
<!-- Begin Content -->

";}}