ETSa:1:{s:4:"main";a:8:{s:4:"2:73";s:61:"
<html>
	<head>
		<title>Insert...</title>
		<LINK HREF="";s:17:"4:85:script_path:";s:0:"";s:5:"2:162";s:76:"skin/style.css" TYPE="text/css" REL="stylesheet"> 
	</head>
	<body>
	
		";s:5:"2:191";s:4:"
		";s:18:"4:203:java_script:";s:0:"";s:5:"2:418";s:214:"
			
		<table width="100%">
			<tr>
				<td width="50%">
					<font size="+1">
						<center>Icon</center>
					</font>
				</td>
				<td>
					<font size="+1">Description</font>
				</td>
			</tr>
			";s:13:"16:430:items:";a:7:{s:5:"2:503";s:73:"
			<tr>
				<td>
					<center>
					<a href="javascript:insertItem('";s:11:"4:508:code:";s:0:"";s:5:"2:524";s:15:"');"><img src="";s:10:"4:528:img:";s:0:"";s:5:"2:583";s:54:"" border="0"></a>
					</center>
				</td>
				<td>";s:11:"4:588:desc:";s:0:"";s:5:"2:609";s:20:"</td>
			</tr>
			";}s:5:"2:727";s:111:"
		</table>
	<p>
	<center>
	<b>Powered by NewLife Blogger 3.0</b>
	</center>
	</p>
	</body>
</html>

";}}