ETSa:1:{s:4:"main";a:5:{s:4:"2:17";s:5:"

	";s:11:"16:28:news:";a:13:{s:5:"2:105";s:77:"

		<div style="padding: 3px; margin: 3px;">
		<span class="news_subject">";s:14:"4:113:subject:";s:0:"";s:5:"2:130";s:16:"</span> <br>
		";s:11:"4:135:body:";s:0:"";s:5:"2:140";s:4:"
		";s:16:"32:154:comments:";a:5:{s:5:"2:174";s:20:"
			<br /><a href="";s:19:"4:187:comments_url:";s:0:"";s:5:"2:200";s:12:"">Comments: ";s:19:"4:213:comments_num:";s:0:"";s:5:"2:222";s:8:"</a>
		";}s:5:"2:232";s:4:"
		";s:17:"128:246:comments:";a:1:{s:5:"2:286";s:40:"
			<br />Comments: <i>Disabled</i>
		";}s:5:"2:344";s:52:"
		<br />
		<span class="news_extra">Posted by <b>";s:13:"4:351:author:";s:0:"";s:5:"2:360";s:8:"</b> on ";s:11:"4:365:date:";s:0:"";s:5:"2:394";s:28:"</span>
		
		</div>
		
	";}s:5:"2:407";s:6:"
	
	";s:21:"32:426:view_comments:";a:10:{s:5:"2:429";s:3:"
	";s:5:"2:539";s:52:"
		
		<div class="title">Comments:</div>
				
		";s:21:"16:559:list_comments:";a:9:{s:5:"2:667";s:108:"
			<div class="comment">
				<fieldset class="comment">
					<legend class="comment">
						<b>
						";s:14:"128:678:guest:";a:5:{s:5:"2:687";s:9:"<a href="";s:25:"4:706:author_url_profile:";s:0:"";s:5:"2:709";s:2:"">";s:13:"4:716:author:";s:0:"";s:5:"2:721";s:4:"</a>";}s:5:"2:735";s:8:"
						";s:13:"32:746:guest:";a:1:{s:13:"4:753:author:";s:0:"";}s:5:"2:783";s:23:"
						</b> Posted on ";s:11:"4:788:date:";s:0:"";s:5:"2:812";s:23:"
					</legend>
					";s:11:"4:817:body:";s:0:"";s:5:"2:850";s:32:"
				</fieldset>
			</div>
		";}s:5:"2:943";s:86:"
		
		<fieldset class="comment">
			<legend>Add Comment</legend>
			<center>
				";s:18:"4:955:add_comment:";s:0:"";s:5:"2:960";s:4:"<br>";s:18:"4:972:link_bbcode:";s:0:"";s:5:"2:974";s:1:" ";s:18:"4:986:link_smiles:";s:0:"";s:6:"2:1022";s:35:"
			</center>
		</fieldset>
	
	";}s:6:"2:1032";s:4:"

";}}