ETSa:3:{s:4:"form";a:5:{s:4:"2:47";s:36:"

	<h3>Search the blogs</h3>
	
	";s:16:"32:62:noresults:";a:1:{s:5:"2:101";s:39:"No blogs were found matching your query";}s:5:"2:147";s:40:"
	
	<p>
	<form method="post" action="";s:17:"4:158:url_search:";s:0:"";s:5:"2:522";s:363:"">
		Search for this text: <input type="text" name="q" size="60" />
		<br /><label><input type="checkbox" name="subject"> In the subject</label>
		<br /><label><input type="checkbox" name="body" checked="checked"> In the body</label>
		<br />Posted by author: <input type="text" name="author">
		<br /><input type="submit" value="Search!">
	</form>
	</p>
";}s:7:"results";a:9:{s:5:"2:575";s:24:"

	<strong>There were ";s:14:"4:583:matches:";s:0:"";s:5:"2:621";s:37:" entries found:</strong>

	<div>
	";s:16:"32:635:url_prev:";a:3:{s:5:"2:644";s:9:"<a href="";s:15:"4:653:url_prev:";s:0:"";s:5:"2:664";s:10:"">Back</a>";}s:5:"2:673";s:3:"
	";s:16:"32:687:url_next:";a:3:{s:5:"2:696";s:9:"<a href="";s:15:"4:705:url_next:";s:0:"";s:5:"2:716";s:10:"">Next</a>";}s:5:"2:744";s:22:"
	</div>
	
	<ul>
	";s:15:"16:758:entries:";a:15:{s:5:"2:771";s:13:"
		<li>
			";s:13:"4:778:author:";s:0:"";s:5:"2:782";s:3:" @ ";s:11:"4:787:date:";s:0:"";s:5:"2:810";s:22:": <br />
			<a href="";s:10:"4:814:url:";s:0:"";s:5:"2:817";s:2:"">";s:14:"4:825:subject:";s:0:"";s:5:"2:839";s:13:"</a> 
			<p>";s:11:"4:844:body:";s:0:"";s:5:"2:847";s:2:" (";s:15:"4:856:comments:";s:0:"";s:5:"2:865";s:8:" Comment";s:18:"256:881:comments:1";a:1:{s:5:"2:882";s:1:"s";}s:5:"2:902";s:17:")</p>
		</li>
	";}s:5:"2:922";s:13:"
	</ul>
	
";}s:8:"redirect";a:5:{s:6:"2:1014";s:70:"

	Your results are being procesed and will be shown here: <a href="";s:11:"4:1018:url:";s:0:"";s:6:"2:1132";s:113:"">Click if you are not redirected</a>
	
	<script language="javascript" type="text/javascript">window.location="";s:11:"4:1136:url:";s:0:"";s:6:"2:1153";s:16:"";</script>
	
";}}