{mask:main}

<table class="nlb_table" width="97%">

	<tr>
		<th colspan="2"><font face="Georgia" size="4" color="#000000"><b>{subject}</b></font></td>
	</tr>
	<tr>
		<th>
			By 
			<a class="b" href="{author_url_blogs}" onMouseOver="return overlib('<a href={author_url_blogs}>See Blogs</a><br><a href={author_url_profile}>See Profile</a>', CAPTION, '{author}\'s Info', STICKY, CLOSECLICK, TIMEOUT, '5000');" onMouseOut="nd();">
				<font color="#ffffff">{author}</font>
			</a>
		</th>
		<th>
			{date}
		</th>
	</tr>
	<tr>
		<td colspan="2">
			{body}
		</td>
	</tr>

</table>

{/mask}