<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<title>{username}'s Profile</title>
<style type="text/css">
<!--
{#

a:link { color: #000000; }
a:hover { color: #333333; }
a:visited { color: #000000; }
a:active { color: #666666; }

a:link.nav { color: #FFFFFF; }
a:hover.nav { color: #FFFFFF; }
a:visited.nav { color: #FFFFFF; }
a:active.nav { color: #FFFFFF; }

td {
	font-size: 12px;
	font-face: Arial, Helvetica
}

#}
-->
</style>
</head>
<body bgcolor="#FFFFFF" text="#000000">

<table border="0" width="500" cellpadding="0" cellspacing="0" align="center">
 <tr>
  <td width="350" valign="bottom">
   <table border="0" cellspacing="0" cellpadding="2" bgcolor="#000000">
    <tr>
     <td>
      <font face="Arial, Helvetica" size="2" color="#FFFFFF">
       <a href="{url_home}" class="nav">Home</a>
       <a href="{url_profile}" class="nav">Profile</a>
       <a href="{url_friends}" class="nav">Friends</a>
      </font>
     </td>
    </tr>
   </table>
  </td>
  <td align="right" valign="bottom">
   <a href="%HOME_LINK%"><font face="Arial" size="3" color="#000000"><b>%HOME%</b></font></a>
  </td>
 </tr>
 <tr colspan="2" bgcolor="#000000">
  <td bgcolor="#000000" colspan="2">
   <table width="100%" border="0" cellspacing="2" cellpadding="0" bgcolor="#000000"><tr><td>
   <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#FFFFFF">
    <tr>
     <td bgcolor="ffcc33">

	<font face="Arial, Helvetica" size="2">
			<table width="90%" align="center">
        <tr>
          <td>Avatar:</td>
          <td>{avatar}</td>
        </tr>
        <tr>
          <td>email: </td>
          <td>{email}</td>
        </tr>
        <tr>
          <td>Public Blogs: </td>
          <td>{blog_count}</td>
        </tr>
        <tr>
          <td>Posted Comments: </td>
          <td>{comment_count}</td>
        </tr>
        <tr>
          <td>Birthday: </td>
          <td>{birthday}</td>
        </tr>
        <tr>
          <td>Gender: </td>
          <td>{gender}</td>
        </tr>
        <tr>
          <td>Friends: </td>
          <td>{num_friends}</td>
        </tr>
          <td>People who list me as a friend:</td>
          <td>{num_as_friend}</td>
        </tr>
        <tr>
          <td>Date registered: </td>
          <td>{registered}</td>
        </tr>
        <tr>
          <td valign="top">Bio: </td>
          <td> {bio} </td>
        </tr>
      </table>
     </td>
    </tr>
   </table>
   </td></tr></table>
  </td>
 </tr>
 <tr colspan="2">
  <td align="center" colspan="2">
   <font face="Arial, Helvetica" size="1">
    Copyright &copy; 2003 {username}	
   </font>
  </td>
 </tr>
</table>
</body>
</html>
<!--
	Template: I Hate Salem
	Source: www.oswd.org
	Author: BrAInDeD- [http://www.oswd.org/userinfo.phtml?user=BrAInDeD-]
-->